### ISSUE TITLE
Starting git clone

### ISSUE THREAD

**Issue by bi3mw** [D-Brox/pysheng3#4]
I cannot log in with my username and password:

"remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead."

**Comment by D-Brox** [comment]
This is probably and issue with your git global configuration. I suggest looking [here](https://namespaceit.com/blog/remote-support-for-password-authentication-was-removed-on-august-13-2021-please-use-a-personal-access-token-instead).
